# Generated by Django 4.2.5 on 2023-12-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ('subject', 'collection_event', 'sample_type')},
        ),
        migrations.RemoveField(
            model_name='sample',
            name='location',
        ),
        migrations.AlterField(
            model_name='sample',
            name='collection_status',
            field=models.CharField(choices=[('Collected', 'Collected'), ('Not Collected', 'Not Collected'), ('Pending', 'Pending')], default='Pending', max_length=15),
        ),
    ]
