# Generated by Django 4.2.5 on 2023-12-18 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0002_alter_sample_options_remove_sample_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_ui', models.CharField(blank=True, max_length=6, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('consent_status', models.CharField(choices=[('Consented', 'Consented'), ('Not Consented', 'Not Consented'), ('Withdrawn', 'Withdrawn'), ('Inactive', 'Inactive')], default='Consented', max_length=15)),
                ('consent_date', models.DateField(blank=True, null=True)),
                ('withdrawn_date', models.DateField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ('location', 'created_on'),
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='week',
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='source',
            field=models.CharField(blank=True, choices=[('Human', 'Human'), ('Dog', 'Dog'), ('Cat', 'Cat'), ('Rat', 'Rat'), ('Mouse', 'Mouse'), ('Horse', 'Horse'), ('Cow', 'Cow'), ('Donkey', 'Donkey'), ('Pig', 'Pig')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(blank=True, choices=[('Urine', 'Urine'), ('Soil', 'Soil'), ('Trap', 'Trap'), ('Carcass', 'Carcass')], max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='SampleType',
        ),
        migrations.AddField(
            model_name='subject',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lims.location'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lims.subject'),
        ),
        migrations.DeleteModel(
            name='Species',
        ),
    ]
