# Generated by Django 4.2.5 on 2023-12-18 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0003_subject_remove_event_week_location_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='neigborhood',
            new_name='neighborhood',
        ),
    ]
