# Generated by Django 4.2.5 on 2023-12-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0004_rename_neigborhood_location_neighborhood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='family_name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_ui',
        ),
        migrations.AddField(
            model_name='subject',
            name='given_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
