# Generated by Django 4.2.5 on 2023-12-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0005_rename_name_subject_family_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='family_name',
        ),
        migrations.AlterField(
            model_name='subject',
            name='given_name',
            field=models.CharField(default='name', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
