# Generated by Django 4.2.5 on 2024-01-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0006_remove_subject_family_name_alter_subject_given_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='family_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='given_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('given_name', 'family_name')},
        ),
    ]
