# Generated by Django 4.2.5 on 2024-01-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0009_animal_subject_contact_email_subject_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalsurvey',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='housesurvey',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='residentsurvey',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='animalsurvey',
            name='cause_of_death',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
