# Generated by Django 4.2.5 on 2024-01-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0010_animalsurvey_created_on_housesurvey_created_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housesurvey',
            old_name='number_or_residents',
            new_name='number_of_residents',
        ),
        migrations.AddField(
            model_name='housesurvey',
            name='number_of_residents_sampled',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
