# Generated by Django 4.2.5 on 2024-01-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0011_rename_number_or_residents_housesurvey_number_of_residents_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residentsurvey',
            old_name='barefood_around_house',
            new_name='barefoot_around_house',
        ),
        migrations.AddField(
            model_name='residentsurvey',
            name='barefoot_around_house_notes',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='residentsurvey',
            name='boil_water_notes',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
