# Generated by Django 5.0.1 on 2025-03-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0012_rename_barefood_around_house_residentsurvey_barefoot_around_house_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='lab',
            field=models.TextField(blank=True, null=True),
        ),
    ]
