# Generated by Django 5.0.1 on 2025-03-07 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0015_remove_sampleresult_unique_sample_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleresult',
            name='run_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='sampleresult',
            name='run_rep',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
