# Generated by Django 5.0.1 on 2025-03-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0016_sampleresult_run_date_sampleresult_run_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleresult',
            name='dye',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='limit',
            field=models.SmallIntegerField(default=40),
        ),
    ]
