# Generated by Django 5.0.1 on 2025-03-07 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0018_alter_sampleresult_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='limit',
            new_name='threshold',
        ),
    ]
