# Generated by Django 5.0.1 on 2025-03-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0019_rename_limit_test_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleresult',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
