# Generated by Django 5.0.1 on 2025-03-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0020_alter_sampleresult_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='threshold',
            field=models.FloatField(default=40),
        ),
    ]
