# Generated by Django 5.0.1 on 2025-03-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0021_alter_test_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleresult',
            name='run_rep',
        ),
        migrations.AddField(
            model_name='sampleresult',
            name='run_name',
            field=models.CharField(default='Run1', max_length=64),
        ),
    ]
