# Generated by Django 5.0.1 on 2025-03-10 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0023_remove_sampleresult_dye_sample_shipped_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='shipped',
        ),
    ]
