from django.urls import path
from . import views

app_name = 'lims'

urlpatterns = [
    path('', views.index, name="index"),
    path('help/', views.help, name="help"),
    path('samples/search/', views.search_view, name="sample_search"),
    path('fix-ids/', views.fix_ids, name="fix_ids"),
    path('samples/', views.SampleListView.as_view(), name="sample_list"),
    path('samples/add/', views.add_samples, name="new_samples"),
    path('samples/detail/<str:pk>/edit/', views.SampleUpdateView.as_view(), name="edit_sample"),
    path('samples/json/', views.sample_list_json_view, name="sample_list_json"),
    path('samples/detail/<str:pk>/', views.SampleDetailView.as_view(), name="sample_detail"),
    path('samples/table-edit/', views.sample_table_update_view, name="sample_table_update"),
    path('locations/', views.LocationListView.as_view(), name="location_list"),
    path('locations/new/', views.LocationFormView.as_view(), name="new_location"),
    path('locations/detail/<str:pk>/', views.LocationDetailView.as_view(), name="location_detail"),
    path('locations/detail/<str:pk>/edit/', views.LocationUpdateView.as_view(), name="edit_location"),
    path('locations/detail/<str:pk>/remove/', views.LocationDeleteView.as_view(), name="delete_location"),
    path('neighborhoods/', views.NeighborhoodListView.as_view(), name="neighborhood_list"),
    path('neighborhood/new/', views.NeighborhoodFormView.as_view(), name="new_neighborhood"),
    path('neighborhoods/detail/<str:pk>/', views.NeighborhoodDetailView.as_view(), name="neighborhood_detail"),
    path('neighborhoods/detail/<str:pk>/edit/', views.NeighborhoodUpdateView.as_view(), name="edit_neighborhood"),
    path('neighborhoods/detail/<str:pk>/remove/', views.NeighborhoodDeleteView.as_view(), name="delete_neighborhood"),
    path('researchers/', views.ResearcherListView.as_view(), name="researcher_list"),
    path('researchers/new/', views.ResearcherFormView.as_view(), name="new_researcher"),
    path('researchers/detail/<str:pk>/', views.ResearcherDetailView.as_view(), name="researcher_detail"),
    path('researchers/detail/<str:pk>/edit/', views.ResearcherUpdateView.as_view(), name="edit_researcher"),
    path('researchers/detail/<str:pk>/remove/', views.ResearcherDeleteView.as_view(), name="delete_researcher"),
    path('event/', views.EventListView.as_view(), name="event_list"),
    path('event/new/', views.EventFormView.as_view(), name="new_event"),
    path('event/detail/<str:pk>/', views.EventDetailView.as_view(), name="event_detail"),
    path('event/detail/<str:pk>/samples/', views.EventSampleListView.as_view(), name="event_detail_samples"),
    path('event/detail/<str:pk>/samples/form/', views.sample_excel_sheet, name="event_samples_excel"),
    path('event/detail/<str:pk>/new-samples/', views.add_samples, name="new_samples_event"),
    path('event/detail/<str:pk>/samples/upload/', views.upload_sample_file, name="upload_samples"),
    path('event/detail/<str:pk>/print-labels/', views.sample_label_options, name="sample_labels_options"),
    path('event/detail/<str:pk>/edit/', views.EventUpdateView.as_view(), name="edit_event"),
    path('event/detail/<str:pk>/remove/', views.EventDeleteView.as_view(), name="delete_event"),
    path('sample-box/', views.SampleBoxListView.as_view(), name="sample_box_list"),
    path('sequencing/', views.SequenceListView.as_view(), name="sequence_list"),
    path('sample-result/', views.SampleResultListView.as_view(), name="sample_result_list"),
    path('labels/', views.LabelListView.as_view(), name="label_list"),
    path('labels/new/', views.LabelFormView.as_view(), name="new_label"),
    path('labels/detail/<str:pk>/', views.LabelDetailView.as_view(), name="label_detail"),
    path('labels/detail/<str:pk>/edit/', views.LabelUpdateView.as_view(), name="edit_label"),
    path('labels/detail/<str:pk>/remove/', views.LabelDeleteView.as_view(), name="delete_label"),
    path('print-labels/choose-event/', views.select_event_for_sample_labels, name="event_for_labels"),
    path('test/', views.TestListView.as_view(), name="test_list"),
    path('subject/', views.SubjectListView.as_view(), name="subject_list"),
    path('subject/json/', views.subject_list_json_view, name="subject_list_json"),
    path('subject/new/', views.SubjectFormView.as_view(), name="new_subject"),
    path('subject/detail/<str:pk>/', views.SubjectDetailView.as_view(), name="subject_detail"),
    path('subject/detail/<str:pk>/edit/', views.SubjectUpdateView.as_view(), name="edit_subject"),
    path('subject/detail/<str:pk>/remove/', views.SubjectDeleteView.as_view(), name="delete_subject"),
    path('sample-result/new/', views.SampleResultFormView.as_view(), name="new_sample_result"),
    path('samples/detail/<str:pk>/result/new', views.SampleResultSampleFormView.as_view(), name="new_result_sample"),


]